<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Mage
 * @package    Datatrans_Hiddenmode
 * @copyright  Copyright (c) 2012 PHOENIX MEDIA GmbH & Co. KG (http://www.phoenix-media.eu)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if ($_info = $this->getInfo()): ?>
<?php echo Mage::helper('datatrans_hm')->__('Name on the Card: %s', $this->htmlEscape($_info->getCcOwner())) ?><br/>
<?php echo Mage::helper('datatrans_hm')->__('Credit Card Type: %s', $this->htmlEscape($this->getCcTypeName())) ?><br/>
<?php echo Mage::helper('datatrans_hm')->__('Credit Card Number: xxxx-%s', $this->htmlEscape($_info->getCcLast4())) ?><br/>
<?php echo Mage::helper('datatrans_hm')->__('Expiration Date: %s/%s', $this->htmlEscape($this->getCcExpMonth()), $this->htmlEscape($_info->getCcExpYear())) ?>
<?php endif; ?>