<?php echo Mage::helper('datatrans_hm')->__('Name on the Card: %s', $this->htmlEscape($this->getInfo()->getCcOwner())) ?>
    {{pdf_row_separator}}
<?php echo Mage::helper('datatrans_hm')->__('Credit Card Type: %s', $this->htmlEscape($this->getCcTypeName())) ?>
    {{pdf_row_separator}}
<?php echo Mage::helper('datatrans_hm')->__('Credit Card Number: xxxx-%s', $this->htmlEscape($this->getInfo()->getCcLast4())) ?>
    {{pdf_row_separator}}
<?php echo Mage::helper('datatrans_hm')->__('Expiration Date: %s/%s', $this->htmlEscape($this->getCcExpMonth()), $this->htmlEscape($this->getInfo()->getCcExpYear())) ?>
